More test fixes
nationalarchives/ds-caselaw-data-enrichment-service pull request #179
Opened 2023-03-15 17:56 UTC by dragon-dxw

Discovered copy-pasting a test didn't run, so ran pytest to try to diagnose why and found some more tests.

2023-03-15 18:18 UTC, dragon-dxw commented on lambdas
> +lambda
I'm not a fan of this symlink, but I'm loathe to change the directory name without significant care and attention.

2023-03-16 09:02 UTC, anthonyhashemi commented on lambdas
> +lambda
Yeah Im planning on changing the name soon when tackling that reorganise ticket so Ill deal with that then

2023-03-16 09:04 UTC, jacksonj04 commented on lambdas
> +lambda
👍🏻

2023-03-16 09:05 UTC, anthonyhashemi commented on README.md
>  You can also obtain a test coverage report with `coverage run --source . -m unittest && coverage report`
I think we should we just delete unittest to keep things simpler. I know that will mean adjusting a lot of the test classes that depend on TestCase or something so happy for that to be done later - I can make a ticket for it

2023-03-16 09:07 UTC, jacksonj04 requested changes
Happy with all these changes, but could we also add an `include` statement in a `.coveragerc` file to make sure we're getting coverage on all the source files even if they're not hit by a test? The fact adding tests has reduced coverage makes me twitchy!

2023-03-16 13:30 UTC, dragon-dxw commented on lambdas
> +lambda
<3

2023-03-16 13:37 UTC, dragon-dxw commented on README.md
>  You can also obtain a test coverage report with `coverage run --source . -m unittest && coverage report`
I've fixed this bit of the docs -- it's pytest in the CI.

I'm not convinced it's worth it -- if it gets in the way, sure, go for it; but I don't think it' something that has enough impact on us to justify the time.

That said, you disagree, so go for it... :)

2023-03-20 11:51 UTC, dragon-dxw commented
![](https://github.trello.services/images/mini-trello-icon.png) [More Test Fixes: Enrichment](https://trello.com/c/pgqIEVsk/665-more-test-fixes-enrichment)

2023-03-20 12:49 UTC, anthonyhashemi approved these changes

2023-03-20 12:52 UTC, jacksonj04 approved these changes

2023-03-20 12:57 UTC, merged