Use xml parsing for first stage replacements
nationalarchives/ds-caselaw-data-enrichment-service pull request #670
Opened 2024-11-25 14:34 UTC by dragon-dxw

## Changes in this PR:

### Jira card / Rollbar error (etc)

- [ ] Increase the version number in src/lambdas/determine_legislation_provisions/index.py
- [ ] Update CHANGELOG.md
- [ ] Requires env variable(s) to be updated

2024-11-25 16:03 UTC, dragon-dxw commented on src/replacer/replacer_pipeline.py
> +def assert_not_bad(s):
We could replace this with an lxml scan. We might not need it every time.

2024-11-25 16:03 UTC, dragon-dxw commented on src/replacer/replacer_pipeline.py
> +    ### DRAGON: use utils.proper_xml.create_tag_string when creating. But for now, focus on making it not change attributes, only XML running text
TODO

2024-11-25 16:04 UTC, dragon-dxw commented on src/tests/fixtures/broken.txt
> +{"leg": ["Sale of Goods Act 1979", "http://www.legislation.gov.uk/id/ukpga/1979/54", "1979 c. 54"]}
Note: this is real data, and we should be cautious about using it.

2024-11-25 16:04 UTC, dragon-dxw commented on src/tests/replacer_tests/test_make_replacements.py
> +        original_file_content = open(f"{FIXTURE_DIR}/broken.xml", encoding="utf-8").read()
consider `FIXTURE_DIR / xxx`

2024-11-25 16:05 UTC, dragon-dxw commented on src/tests/replacer_tests/test_make_replacements.py
> +        original_file_content = open(f"{FIXTURE_DIR}/broken.xml", encoding="utf-8").read()
consider more descriptive fixture name

2024-11-25 16:05 UTC, dragon-dxw commented on src/replacer/replacer_pipeline.py
> +    assert_not_bad(file_data)
Just the once should do when not actively debugging.

2024-11-25 16:05 UTC, dragon-dxw commented on src/utils/proper_xml.py
> +"""
Consider making this take multiple replacements at once for speed?

2024-11-25 16:06 UTC, dragon-dxw commented on src/utils/tests/test_proper_xml.py
> +        """Ideally, this should have <cite/> - <cite/> in the output, instead of just doing the first; we could rerun until it runs clean"""
TODO

2024-11-25 16:06 UTC, dragon-dxw commented on src/utils/tests/test_proper_xml.py
> +    def test_as_text_quotes(self):
Any insights as to the right way to do this would be appreciated.

2024-11-26 17:13 UTC, dragon-dxw commented
We verified that the issue is not reparsing already parsed things -- the failing judgment contains no <ref> tags nor any signatures of being enriched (versions, etc.)

Instead we now think that the enrichment process applies these two rules:

```
('[1971] 1 Q.B. 488', '[1971] 1 QB 488', '1971', '#', False)
('[1971] 1 QB 488', '[1971] 1 QB 488', '1971', '#', False)
```

And sees `[1971] 1 Q.B. 488`, converts that to `<ref id="[1971] 1 QB 488">...</ref>` and then on the second line to `<ref id="<ref id="...">...</ref></ref>`. Which is not valid.

2024-11-28 16:13 UTC, jacksonj04 requested changes
Couple of tiny tweaks, but this looks solid 👍🏻

2024-11-28 16:13 UTC, jacksonj04 commented on src/tests/replacer_tests/test_make_replacements.py
> +    def test_make_failing_post_header_replacements(self):
What's the actual test here? Are we just making sure it doesn't throw an exception?

2024-11-28 16:13 UTC, jacksonj04 commented on src/lambdas/extract_judgement_contents/index.py
> +def extract_text_content(file_content: DocumentAsXMLString) -> DocumentAsXMLString:
Is this actually a string representation of XML? I think it's just a string of all the words in the XML.

2024-11-28 16:13 UTC, jacksonj04 commented on src/utils/helper.py
> +def parse_file(file_data: DocumentAsXMLString) -> DocumentAsXMLString:
Another instance where I think this is a string of text, not a string of XML.

2024-11-28 16:13 UTC, jacksonj04 commented on src/oblique_references/oblique_references.py
> +    all_replacements: list[LegislationReferenceReplacement] = []
Should this be `LegislationReferenceReplacements`? instead of the `list[]`?

2024-11-28 16:13 UTC, jacksonj04 commented on src/oblique_references/oblique_references.py
> +        replacements: list[LegislationReferenceReplacement] = []
Should this be `LegislationReferenceReplacements`? instead of the `list[]`?

2024-11-28 16:28 UTC, dragon-dxw commented on src/tests/replacer_tests/test_make_replacements.py
> +    def test_make_failing_post_header_replacements(self):
Write a small actual test that fails, should be OK.

2024-11-28 16:28 UTC, dragon-dxw commented on src/tests/replacer_tests/test_make_replacements.py
> +    def test_make_failing_post_header_replacements(self):
Assert correct exception would be great.

2024-11-28 16:29 UTC, dragon-dxw commented on src/lambdas/extract_judgement_contents/index.py
> +def extract_text_content(file_content: DocumentAsXMLString) -> DocumentAsXMLString:
👍

2024-11-28 16:29 UTC, dragon-dxw commented on src/utils/helper.py
> +def parse_file(file_data: DocumentAsXMLString) -> DocumentAsXMLString:
:+1:

2024-11-28 16:30 UTC, dragon-dxw commented on src/oblique_references/oblique_references.py
> +    all_replacements: list[LegislationReferenceReplacement] = []
use list[LegislationReferenceReplacement] throughout instead.

2024-11-28 16:30 UTC, dragon-dxw commented on src/oblique_references/oblique_references.py
> +        replacements: list[LegislationReferenceReplacement] = []
see above, invert.

2024-11-29 13:28 UTC, jacksonj04 commented on src/tests/fixtures/broken.txt
> +{"leg": ["Sale of Goods Act 1979", "http://www.legislation.gov.uk/id/ukpga/1979/54", "1979 c. 54"]}
I'm not worried about this; nothing here is sensitive or secret, and it makes testing more reliable.

2025-01-08 11:18 UTC, merged